# Generated by Django 2.0.6 on 2018-11-04 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20181030_2007'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='write_members',
        ),
        migrations.AddField(
            model_name='team',
            name='write',
            field=models.BooleanField(default=False),
        ),
    ]
