# Generated by Django 2.0.6 on 2018-12-03 20:08

from django.db import migrations, models
import projects.models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20181104_2047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskfile',
            name='file',
            field=models.FileField(storage=projects.models.OverwriteStorage(), upload_to=projects.models.directory_path),
        ),
    ]
